### ISSUE TITLE
Email collector / newsletter

### ISSUE THREAD

**Issue by zakpatterson** [bike-grid-now/bike-grid-monorepo#9]
Should we have a place for users to provide their email? Should we send them a newsletter or upcoming event notification that way?

**Comment by zakpatterson** [comment]
I understand we're currently collecting emails here: 

https://actionnetwork.org/events/cgbn-halsted-bike-bus-commuters-take-action-protest-run

Can those contacts be pulled out?

**Comment by samwightt** [comment]
@zakpatterson [We have one here](https://newsletter.bikegridnow.org)! There's a link under there under "Newsletter Signup".

**Comment by zakpatterson** [comment]
Hm, yes... improved link text in #17
